### ISSUE TITLE
Prepare submittion to RubyGems.org

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#12]
We'll distribute `fluent-plugin-windows-exporter` as a Ruby gem.

Note: The installation process should be very streaght foraward, because
this plugin is written in  pure Ruby and does not depend on C libraries. So
`gem install fluent-plugin-windows-exporter` must just work.

**Comment by fujimotos** [comment]
The remaining TODO list is actually small. After I did some more test, I will
publish the initial release.

**TODO**

- [x] Release v1.0.0 on GitHub
- [x] Push gem to RubyGems.org
- [x] Add @daipom as the owner to gem

**Comment by daipom** [comment]
I have confirmed the released gem to work correctly.

**Comment by fujimotos** [comment]
Initial release published!
