### ISSUE TITLE
Improve the data collecting performance on Windows

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#8]
This ticket tracks the status of data collecting performance on Windows.

### TODO

1. [x] Get the statistics of the performance of this plugin
    * How many CPU resource this plugin use?
    * How much time it takes to collect metrics?
2. [x] Compare the performance with `prometheus-community/windows-exporter`
    * Compare CPU usage and time (Prometheus vs Fluentd)
3. [x] If there is a major difference between Prometheus and Fluentd, investigate the reason.
4. [x] Compare the performance of `Global` vs `OLD_Global`
    * Check if using `OLD_Global` improves the CPU usage/collection time or not
    * [OLD_Global is an older API that only supports v1 metrics, so it may well be more lightweight than Global](https://docs.microsoft.com/en-us/windows/win32/perfctrs/using-the-registry-functions-to-consume-counter-data)
5. [x] Make it sure that `fluent-plugin-windows-exporter` does not block Fluentd startups
    * Defer  `HKEY_PERFORMANCE_*` loading, so that other input plugins won't get delayed by slow access to WIndows Registry.

**Comment by fujimotos** [comment]
**TODO**

1. Evaluate the performance of this plugin
  * Metrics: CPU usage + collection time 
2. Compare the performance with `prometheus-community/windows-exporter`
  * How the performance of this plugin compare? 
  * Metrics: CPU usage + collection time
3. Compare the performance of `Global` vs `Global_old`
  * See if using `Global_old` improves the perforamnce or not

**Comment by daipom** [comment]
I ran fluentd and prometheus-windows-exporter for 10 minutes each and compared them by the elapsed time [sec].

fluentd is installed by ruby gem and executed by `fluentd -c ./fluent/fluent.conf`.
Then 2 ruby processes are launched, so I monitor these 2 ruby processes.
Plugin: 8c11c22180fd3d513329891df3a2c6b9d893ab84
Gem info: `fluentd (1.14.3 x64-mingw32, 1.12.3 x64-mingw32, 1.12.2)`
The configuration of the plugin is default as follows.

```
<source>
  @type windows_exporter
  tag windows_exporter
</source>
<match windows_exporter>
  @type file
  path {output_path}
</match>
```
 
prometheus-windows-exporter is `0.16.0`, and executed by `.\windows_exporter.exe --collectors.enabled="cpu,memory,logical_disk,net,os"`.
In order to make it to collect data every 60 seconds, I ran a python script too.
[prometheus_free_zero_page.zip](https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/files/7743356/prometheus_free_zero_page.zip)

* WorkingSetPrivate of each process
![2021-12-20_16h22_39](https://user-images.githubusercontent.com/12229857/146728669-75b6430e-2713-451b-862c-664726d5654e.png)

* ProcessorTime of each process
![2021-12-20_16h23_55](https://user-images.githubusercontent.com/12229857/146728825-94ab4f1d-0064-4641-b09d-d7dc7b6ba98e.png)

* CommittedByteInUse of the machine
![2021-12-20_16h26_15](https://user-images.githubusercontent.com/12229857/146728833-453078e0-7b18-4e2d-a247-2ff7bb8e5b48.png)

* ProcessorTime of the machine
![2021-12-20_16h27_57](https://user-images.githubusercontent.com/12229857/146728838-49dd00fe-b1fa-4194-ab03-4acb562f25f1.png)

**Comment by daipom** [comment]
About ProcessorTime of each process.

This shows our plugin use much larger CPU than prometheus.

These data were taken every 2~3 seconds, so some peaks are missing,
but we can assume that our plugin will consume nearly 100% of `ProcessorTime` every time it collects data.

On the other hand, prometheus windows exporter consume very little `ProcessorTime` .

**Comment by fujimotos** [comment]
>  This shows our plugin use much larger CPU than prometheus.
> These data were taken every 2~3 seconds, so some peaks are missing,
> but we can assume that our plugin will consume nearly 100% of ProcessorTime every time it collects data.

Hmm. why does this happen?  Although Ruby is not as fast as Go,
it is _way_ slower than expected. Where is the bottleneck?

**Comment by daipom** [comment]
@fujimotos I am investigating it.
It's possible that I am missing some specifications on the prometheus side, and it's not a valid comparison.

**Comment by fujimotos** [comment]
OK. Let's use tomorrow to investigate this issue together. I guess there
must be some very expensive Ruby code in our implementation...

**Comment by fujimotos** [comment]
> It's possible that I am missing some specifications on the prometheus side, and it's not a valid comparison.

OK. Let's use tomorrow to investigate this issue together. I guess there
must be some very expensive Ruby code in our implementation...

**Comment by daipom** [comment]
I checked the time of taking data.
the processing speed of prometheus is amazingly fast.

* HKeyPerfDataReader of our plugin: average 1.30 s
```ruby
require_relative 'hkey_perf_data_reader'
require 'benchmark'

reader = HKeyPerfDataReader::Reader.new()
10.times do
  result = Benchmark.realtime do
    reader.read
  end
  p result
end
```
```
1.3728787000000011
1.2953287999998793
1.3175160000000687
1.3094750000000204
1.2864519000004293
1.2640043999999762
1.2738070999994306
1.2869583000001512
1.2681265000001076
1.3366325999995752
```

* prometheus: average 0.0490 s
```ruby
require 'benchmark'
require 'uri'
require 'net/http'

10.times do
  result = Benchmark.realtime do
    uri = URI("http://localhost:9182/metrics")
    Net::HTTP.get_response(uri)
  end
  p result
end
```
```
0.07282749999922089
0.04686459999993531
0.046995800000331656
0.04541530000005878
0.045455999999830965
0.047042200000760204
0.047160600000097475
0.04574360000060551
0.04586409999956231
0.046821599999930186
```

**Comment by daipom** [comment]
I also tried the following python script to see if the cache was working and not completely refreshing the data every time.
It turned out that prometheus takes the data every time very quickly.

* python script calling prometheus-windows-exporter uri 10 times and stock taken data. After calling 10 times, this parse the all data and check if the value was updated every time.
```python
import requests
import json
import csv
import datetime
import time


class Record:
    def __init__(self, name):
        self.name = name
        self.labels = {}
        self.value = 0

    def __str__(self):
        return f"{self.name}: {self.labels} : {self.value}"


def parse_all_metrics(response):
    lines = [line.strip() for line in response.text.split("\n") if line.strip() != ""]
    lines = [line for line in lines if not line.startswith("#")]

    prometheous_records = []

    for line in lines:
        i = line.find("{")
        no_label_data = i == -1
        if no_label_data:
            i = line.find(" ")
            record = Record(line[:i])
            record.value = float(line[i+1:])
            prometheous_records.append(record)
        else:
            record = Record(line[:i])
            end_label_i = line.find("}")
            record.value = float(line[end_label_i+1:])
            label = line[i+1:end_label_i]
            while True:
                i = label.find("=\"")
                if i == -1:
                    break
                key = label[:i]
                end_val_i = label.find("\"", i+2)
                val = label[i+2:end_val_i]
                record.labels[key] = val
                label = label[end_val_i+2:]
            prometheous_records.append(record)

    return prometheous_records


def get_metrics_value(response, metrics_name):
    records = parse_all_metrics(response)
    return [r for r in records if r.name == metrics_name]


def main():
    responses = []
    
    for i in range(10):
        start_time = time.perf_counter()
        responses.append(requests.get('http://localhost:9182/metrics'))
        end_time = time.perf_counter()
        elapsed_time = end_time - start_time
        print(elapsed_time)

    for r in responses:
        v = get_metrics_value(r, "windows_memory_free_and_zero_page_list_bytes")[0].value
        print(v)

if __name__ == '__main__':
    main()
```
```
0.0437322
0.040308800000000006
0.04509690000000002
0.046951999999999994
0.04490480000000002
0.0439793
0.0468499
0.04367439999999995
0.047758100000000026
0.045852000000000004
187428864.0
186728448.0
191315968.0
192929792.0
194768896.0
188952576.0
187244544.0
188633088.0
192729088.0
192884736.0
```

**Comment by daipom** [comment]
> > It's possible that I am missing some specifications on the prometheus side, and it's not a valid comparison.
> 
> OK. Let's use tomorrow to investigate this issue together. I guess there must be some very expensive Ruby code in our implementation...

Thank you.
There are still some parts that I could look into, so I'll keep digging.

**Comment by daipom** [comment]
To narrow down the bottleneck, I measured the process separately.

* A: Process of reading raw data by using mainly fiddle.
* B: Process of parsing raw data in our ruby implementation and `Bindata` library.

The result shows B is the bottleneck.

* A: 0.20 sec
* B: 1.1 sec

It's also puzzling that A alone takes about five times as long as prometheus.

```diff
--- a/lib/fluent/plugin/hkey_perf_data_reader.rb
+++ b/lib/fluent/plugin/hkey_perf_data_reader.rb
@@ -64,8 +64,8 @@ module HKeyPerfDataReader
       @logger = logger.nil? ? NullLogger.new : logger
     end

-    def read
-      @raw_data = RawReader.read(@logger)
+    def read(raw_data = nil)
+      @raw_data = raw_data.nil? ? RawReader.read(@logger) : raw_data
```

```ruby
require_relative 'hkey_perf_data_reader'
require 'benchmark'

p "Read RawData by fiddle"

raw_data_list = []
3.times do
  result = Benchmark.realtime do
    raw_data_list.append(HKeyPerfDataReader::RawReader.read)
  end
  p result
end

p "Parse RawData in ruby"

reader = HKeyPerfDataReader::Reader.new()
raw_data_list.each do |raw_data|
  result = Benchmark.realtime do
    reader.read(raw_data)
  end
  p result
end
```
```
"Read RawData by fiddle"
0.21421659999941767
0.19898920000014186
0.19797599999947124
"Parse RawData in ruby"
1.135263600000144
1.102677599999879
1.1311918999999762
```

**Comment by daipom** [comment]
Some processes of `Bindata` seem to be the bottlenecks.

*  test_script.rb
```ruby
require_relative 'hkey_perf_data_reader'

reader = HKeyPerfDataReader::Reader.new()
reader.read
```

* get profile as follows
```
$ ruby -rprofile test_script.rb
```

* profile results
```
 %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
  4.46     2.53      2.53   152208     0.02     0.04  BinData::Struct#instantiate_obj_at
  2.97     4.21      1.69   228670     0.01     0.01  BinData::SanitizedField#name_as_sym
  2.85     5.83      1.62    70350     0.02     0.03  HKeyPerfDataReader::Reader#read_counter_value
  2.72     7.37      1.54    76107     0.02     0.03  BinData::IO::Read#read
  2.67     8.89      1.51   152208     0.01     0.02  BinData::Struct#include_obj?
  2.62    10.37      1.49    92917     0.02     0.29  Array#each
  2.56    11.83      1.45    70350     0.02     0.05  HKeyPerfDataReader::ConvertedType::PerfInstance#add_counter
  2.52    13.25      1.43    76104     0.02     0.04  BinData::Struct#define_field_accessors_for
  2.44    14.64      1.39   228372     0.01     0.01  Kernel#define_singleton_method
  2.40    16.01      1.36    76104     0.02     0.05  BinData::Struct#find_obj_for_name
  2.39    17.36      1.36    90620     0.01     0.19  BinData::Struct#snapshot
  2.11    18.56      1.20    74245     0.02     1.06  HKeyPerfDataReader::Reader#set_counters_to_multiple_instance_object
  1.82    19.60      1.03    76104     0.01     0.02  BinData::Struct#base_field_name
  1.77    20.60      1.01    29072     0.03     0.06  BinData::BaseArgProcessor#separate_args
  1.67    21.55      0.95   242987     0.00     0.00  BinData::Base#has_parameter?
  1.64    22.48      0.93    90620     0.01     0.11  BinData::Struct#define_field_accessors
  1.58    23.38      0.90    71791     0.01     0.05  BinData::Uint32le#read_and_return_value
  1.54    24.25      0.87    70350     0.01     0.02  HKeyPerfDataReader::ConvertedType::PerfCounterDef#is_base_counter
  1.52    25.11      0.86   143437     0.01     0.22  Class#new
  1.47    25.94      0.83    72875     0.01     0.03  Array#collect
  1.46    26.77      0.83    90620     0.01     0.20  BinData::Struct#do_read
  1.25    27.48      0.71    29032     0.02     0.09  BinData::MultiFieldArgSeparator#field_names_in_parameters?
  1.24    28.18      0.70    76107     0.01     0.04  BinData::IO::Read#readbytes
  1.19    28.86      0.67    14516     0.05     0.15  BinData::DSLMixin::DSLParser#to_struct_params
  1.08    29.47      0.62    29354     0.02     0.02  BinData::DSLMixin::DSLParser#option?
  1.02    30.05      0.58    76104     0.01     0.01  BinData::Struct::Snapshot#[]=
...
```

**Comment by daipom** [comment]
I will try to solve this problem about `Bindata` tomorrow.
I'll consider if I can implement the current logic without `Bindata` too.

**Comment by fujimotos** [comment]
> I will try to solve this problem about Bindata tomorrow.
> I'll consider if I can implement the current logic without Bindata too.

Another approach might be not to try parse everything, but only those objects
that we actually use in `in_windows_exporter.rb`. In particular:

* `LogicalDisk`
* `Processor Information`
* `Network Information`
* `Memory`

If we detect anything than the four object above, we can skip to the next
object (probably around line 137 of `hkey_perf_data_reader.rb`).

**Comment by fujimotos** [comment]
> I will try to solve this problem about Bindata tomorrow.
> I'll consider if I can implement the current logic without Bindata too.

Another approach might be not to try to parse everything, but parser only the
objects that we actually use in `in_windows_exporter.rb`. In particular:

* `LogicalDisk`
* `Processor Information`
* `Network Information`
* `Memory`

If we detect anything other than the four objects listed above, we can skip to the
next definition. I'm thinking to add a fast return path to somewhere around here:

https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/blob/master/lib/fluent/plugin/hkey_perf_data_reader.rb#L134

**Comment by daipom** [comment]
@fujimotos Thank you. That is a nice idea!

By using the contents of the following document,
we may be able to speed up the process of `Bindata` considerably.
After a few fix, I was able to immediately reduce the parsing time by about 40% at hand! (1.1sec -> 0.65sec)

https://github.com/dmendel/bindata/wiki/FAQ#how-do-i-speed-up-initialization

Tomorrow I'll first try speeding up Bindata and skipping unnecessary processes,
and re-measure speed and memory.

**Comment by daipom** [comment]
I speeded up the parsing process of bindata at 9862504868a3e3010181ad4405f7ba8bd6ba8095.
This speeds up the process of `HKeyPerfDataReader::Reader::read`
from 1.3 sec to 0.57 sec.

```ruby
require_relative 'hkey_perf_data_reader'
require 'benchmark'

reader = HKeyPerfDataReader::Reader.new()
3.times do
  result = Benchmark.realtime do
    reader.read
  end
  p result
end
```
```
0.5707406999999876
0.5649305000001732
0.5736734000001888
```

**Comment by daipom** [comment]
> Another approach might be not to try to parse everything, but parser only the objects that we actually use in `in_windows_exporter.rb`. In particular:
> 
>     * `LogicalDisk`
> 
>     * `Processor Information`
> 
>     * `Network Information`
> 
>     * `Memory`
> 
> 
> If we detect anything other than the four objects listed above, we can skip to the next definition. I'm thinking to add a fast return path to somewhere around here:
> 
> https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/blob/master/lib/fluent/plugin/hkey_perf_data_reader.rb#L134

@fujimotos I think we need "Paging File" too.

I added a whitelist function at 8876307cdb80100254346c4c685bfa014c877804.
This limits the reading process into reading only the following 5 objects.

* "Processor Information"
* "LogicalDisk"
* "Memory"
* "Network Interface"
* "Paging File"

This has made the reader very quick.
The process of parsing raw data in our ruby implementation and Bindata library is no longer the bottleneck.
Now the bottleneck is the process of reading raw data by using mainly fiddle.

* Entire reading process: 0.20 sec
  * yesterday: 1.3 sec -> improve bindata: 0.57 sec -> whitelist: 0.20 sec
* Process of reading raw data by using mainly fiddle: 0.18 sec
  * This is not doing any speedup process
* Process of parsing raw data in our ruby implementation and Bindata library: 0.028 sec

---

* Entire reading process
```ruby
require_relative 'hkey_perf_data_reader'
require_relative 'in_windows_exporter'
require 'benchmark'

reader = HKeyPerfDataReader::Reader.new(
  object_name_whitelist: Fluent::Plugin::HKeyPerfDataWhiteList::NAMES
)

3.times do
  result = Benchmark.realtime do
    reader.read
  end
  p result
end
```
```
0.21754070000042702
0.20501100000001315
0.19482550000066112
```

---

* separate process
```diff
--- a/lib/fluent/plugin/hkey_perf_data_reader.rb
+++ b/lib/fluent/plugin/hkey_perf_data_reader.rb
module HKeyPerfDataReader
-    def read
-      @raw_data = RawReader.read(@logger)
+    def read(raw_data = nil)
+      @raw_data = raw_data.nil? ? RawReader.read(@logger) : raw_data
```
```ruby
require_relative 'hkey_perf_data_reader'
require_relative 'in_windows_exporter'
require 'benchmark'

reader = HKeyPerfDataReader::Reader.new(
  object_name_whitelist: Fluent::Plugin::HKeyPerfDataWhiteList::NAMES
)

p "Read RawData by fiddle"

raw_data_list = []
3.times do
  result = Benchmark.realtime do
    raw_data_list.append(HKeyPerfDataReader::RawReader.read)
  end
  p result
end

p "Parse RawData in ruby"

raw_data_list.each do |raw_data|
  result = Benchmark.realtime do
    reader.read(raw_data)
  end
  p result
end
```
```
"Read RawData by fiddle"
0.18492820000028587
0.18339490000016667
0.17443999999977677
"Parse RawData in ruby"
0.028117899999415386
0.034688200000346114
0.013279599999805214
```

**Comment by fujimotos** [comment]
> I think we need "Paging File" too.

Yes, I was forgetting about it.

>  This has made the reader very quick.
> The process of parsing raw data in our ruby implementation and Bindata library is no longer the bottleneck.
> Now the bottleneck is the process of reading raw data by using mainly fiddle.

Nice! I'll check the improved version this afternoon. Wait for me.

**Comment by daipom** [comment]
Thank you!
I'll add some test codes and re-measure performance.

**Comment by daipom** [comment]
I have confirmed the significant improvement in CPU consumption.

I compared `% processor time` in 427f213285bb51026a2b174f5627dc5cf9b27acf (after performance improvements) and a5b1bb5c2b5ced71ce73d091807ae336ce8b3fca (before performance improvements).

Set 3 sec to `scrape_interval ` in order to compare CPU consumption clearly.
I ran each for 3 minutes and graphed the results by elapsed time.

Before the fix, it was recording 70~100% every time. 

After the fix, it's only about 10~25%.

config
```
<source>
  @type windows_exporter
  tag windows_exporter
  scrape_interval 3
</source>
<match windows_exporter*>
  @type file
  path {output_path}
</match>
```

![2021-12-21_14h05_46](https://user-images.githubusercontent.com/12229857/146874388-fc4abb28-e31b-49c9-8e6e-ec15923e9c5e.png)

**Comment by daipom** [comment]
I have also re-compared `% processor time` in fluentd and prometheus_windows_exporter.

* fluentd: 10 ~ 25%
* prometheus: 1.5 ~ 10%

In prometheus, it's strange to sometimes see times when  `% processor time` is zero,
even though the data is being retrieved every 3 seconds.
In less cases, it's about `1.5`, so it could just be a missed peak due to a problem with
the interval between counter-value acquisitions.

prometheus
```
.\windows_exporter.exe --collectors.enabled="cpu,memory,logical_disk,net,os"
```
python script to make prometheus_windows_exporter to update data every 3 sec.
```python
import requests
import time

while True:
    requests.get('http://localhost:9182/metrics')
    time.sleep(3)
```

![2021-12-21_14h32_07](https://user-images.githubusercontent.com/12229857/146876623-4b859f51-5da1-42df-ab33-bcc7b42d63f5.png)

**Comment by daipom** [comment]
The above records can be summarized as follows.

|                                 |  Fluentd  | Prometheus |
|---------------------------------|-----------|------------|
| Time to update data             | 0.20s     | 0.05s      |
| % processor time to update data | 10% ~ 25% | 1.5% ~ 10% |

**Comment by daipom** [comment]
@fujimotos Is the upper difference acceptable to us?

I'll try to see if `OldGlobal` can improve performance some more.

**Comment by fujimotos** [comment]
> I have confirmed the significant improvement in CPU consumption.
> ...
> After the fix, it's only about 10~25%.

OK. Now I can confirm that now our plugin takes <0.5s to collect Windows metrics

```cmd
% fluentd -c exporter.conf
...
2021-12-21 06:30:46 +0000 [debug]: #0 fluent/log.rb:309:debug: Updated Windows counters (0.34s)
2021-12-21 06:30:51 +0000 [debug]: #0 fluent/log.rb:309:debug: Updated Windows counters (0.29s)
2021-12-21 06:30:56 +0000 [debug]: #0 fluent/log.rb:309:debug: Updated Windows counters (0.30s)
```

> |                                 |  Fluentd  | Prometheus |
> |---------------------------------|-----------|------------|
> | Time to update data             | 0.20s     | 0.05s      |
> | % processor time to update data | 10% ~ 25% | 1.5% ~ 10% |

On my instance running on Azure `D2ds v5`, it's more like 8-11% with Fluentd
(screenshot attached). I take a brief look at the new implementation if we can
improve the performance further. WFM.


**Screenshot (Intel Xeon Platinum 8370@2.80Ghz)**

![20211221](https://user-images.githubusercontent.com/8974561/146882867-2629b668-97f2-4e13-941c-92983e74add6.png)

**Comment by daipom** [comment]
We cannot take `Processor Information` when using `Old_Global`.
I haven't checked yet, but it's possible `Processor Information` belongs in the `Costly` category.

https://docs.microsoft.com/en-us/windows/win32/perfctrs/using-the-registry-functions-to-consume-counter-data
> Retrieves performance data for all V1 performance objects registered on the computer except for those included in the Costly category.

Anyway, the comparison looks like the following.
Using `Old_Global` makes the reading process of HKeyPerfDataReader faster as expected.

For an equal comparison,  I excluded `Processor Information` from the whitelist.

|                                     | Global | Old_Global |
|-------------------------------------|--------|------------|
| Time to update data                 | 0.193s | 0.171s     |
| Avg % processor time to update data | 6.10s  | 6.28s     |

Time to update data becomes quicker in the fiddle part as expected.
There seems to be no difference in  `% processor time` .
The difference of average value above may be just an error.

![2021-12-21_15h25_51](https://user-images.githubusercontent.com/12229857/146882854-4ea362ee-96b4-485b-983a-f1093110bb8b.png)

**Comment by fujimotos** [comment]
> We cannot take Processor Information when using Old_Global.
> ...
> The difference of average value above may be just an error.

Thank you for the investigation.

Considering that we cannot pull enough metrics from `Old_Global`, let's keep
using `Global`.

As your graph shows, the performance benefit we can get from `Old_Global`
seems quite neglible anyway.

**Comment by daipom** [comment]
@fujimotos Thank you for the confirmation of the performance!

> Considering that we cannot pull enough metrics from `Old_Global`, let's keep
> using `Global`.

I agree!

**Comment by fujimotos** [comment]
@daipom I'm inclined to think that Prometheus is fast _because_ their
`RegCloseKey()` call is not actually working at all.

To verify this, I modified [perflib/perflib.go#L219](https://github.com/leoluk/perflib_exporter/blob/master/perflib/perflib.go#L219) to something like this:

```go
defer func() {
      fmt.Println("RegCloseKey", syscall.RegCloseKey(syscall.HKEY_PERFORMANCE_DATA));
}()
```

... then I compiled the modified version  with:

```cmd
% git clone https://github.com/prometheus-community/windows_exporter
% cd windows_exporter
% go build
```

The following is the test result on my Windows Server 2022. Bsically their
 `RegCloseKey` call is returning `0x06` (ERROR_INVALID_HANDLE).

```cmd
% .\windows_exporter.exe --collectors.enabled=cpu
...
RegCloseKey The handle is invalid.
RegCloseKey The handle is invalid.
RegCloseKey The handle is invalid.
```

**Comment by daipom** [comment]
@fujimotos Thank you for the investigation. I'll check our plugin performance without `RegCloseKey`.

I fixed to make it sure that this plugin does not block Fluentd startups in be06c6a0ebf0642f87195624042c6dae713d721b.

This fix unintentionally speeds up significantly the reading of HKeyPerfDataReader to 0.08s,
close to the speed of prometheus.

The first two times tend to be slower, then faster.

```ruby
require_relative 'hkey_perf_data_reader'
require_relative 'in_windows_exporter'
require 'benchmark'

reader = HKeyPerfDataReader::Reader.new(
  object_name_whitelist: Fluent::Plugin::HKeyPerfDataWhiteList::NAMES
)

10.times do
  result = Benchmark.realtime do
    reader.read
  end
  p result
end
```
```
0.2506758000017726
0.18766080000204965
0.07916529999783961
0.0864681000020937
0.08604809999815188
0.07782619999852614
0.08508470000015222
0.0866277999994054
0.08024099999965983
0.08969989999968675
```

**Comment by daipom** [comment]
https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/runs/4592047716?check_suite_focus=true#step:5:18

Hmm, in this enverionment, the speed becomes slower... : 0.6411106333333502 sec

at the before, it was 0.43965869999980595 sec.
https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/runs/4591787446?check_suite_focus=true#step:5:18

**Comment by fujimotos** [comment]
@daipom There seems to be a large performance variance on GitHub actions.
I saw it once took > 1.6s on e3f813e8031f2dddb8ce3786e2bc2f4ab0b1af27:

> https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/runs/4591505237?check_suite_focus=true#step:5:18

Re-running the test again passed fine. So I think GitHub CI can sometimes
slow down with no particular/obvious reason.

**Comment by daipom** [comment]
@fujimotos I see. Thank you.

I fixed the test code,  and exclude the first reading process from the measurement.
Then the new result is 0.2575531499999954 sec.
https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/runs/4592187176?check_suite_focus=true#step:5:18

I'm guessing that just changing the timing of loading the counter table made the reading process a lot faster.

**Comment by daipom** [comment]
Trying to open a registry after a long time appears to be a big cost.
The speed may have increased because
the `RawReader::Read` and `RawReader::read_counter_name_table` is now done at close timing.

**Comment by fujimotos** [comment]
> I'm guessing that just changing the timing of loading the counter table made the reading process a lot faster.

Good catch. Makes sense. 

**Note:** I suppose that another expensive path (second to `RegCloseKey()` is
the buffer allcation for `RegQueryValueEx()` here:

https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/blob/master/lib/fluent/plugin/hkey_perf_data_reader.rb#L344

Maybe we can save the buffer to a instance variable (something like `@buffer`) and reuse it
for multiple retrievals, instead of allocating one each time.

**More Note:** But I don't think the buffer reusing mentioned above is something we must to do;
As I see it, the current performance is good enough for the initial release.

**Comment by daipom** [comment]
I have checked `RegCloseKey`, although it's already almost as fast as prometheus in my environment.
I measured the speed of the reading process without `RegCloseKey` as follows.

It will be a little faster. 

* With `RegCloseKey`: Average reading time 0.07599737900003674 sec (try 100 times)
* Without `RegCloseKey`: Average reading time 0.0733074159998796 sec (try 100 times)

```diff
--- a/lib/fluent/plugin/hkey_perf_data_reader.rb
+++ b/lib/fluent/plugin/hkey_perf_data_reader.rb
@@ -358,7 +358,8 @@ module HKeyPerfDataReader

         return data[0..unpackdw(size)]
       ensure
-        ret = API.RegCloseKey(hkey)
+        # ret = API.RegCloseKey(hkey)
+        ret = ERROR_SUCCESS
         unless ret == ERROR_SUCCESS
           logger&.warn("RegCloseKey failed with #{ret}.")
         end
```

**Comment by daipom** [comment]
> **Note:** I suppose that another expensive path (second to `RegCloseKey()` is the buffer allcation for `RegQueryValueEx()` here:
> 
> https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/blob/master/lib/fluent/plugin/hkey_perf_data_reader.rb#L344
> 
> Maybe we can save the buffer to a instance variable (something like `@buffer`) and reuse it for multiple retrievals, instead of allocating one each time.
> 
> **More Note:** But I don't think the buffer reusing mentioned above is something we must to do; As I see it, the current performance is good enough for the initial release.

OK! Thank  you! I will add the comment for the future fix.

**Comment by daipom** [comment]
I will re-measure the performance last time, then I think we can close this issue.

**Comment by fujimotos** [comment]
> I have checked RegCloseKey, although it's already almost as fast as prometheus in my environment.
> ...
> It will be a little faster.

Hmm. I retested on 7da2b706bd7d73b5f00876fcaae085b5a8924230,  and didn't see much difference too
(either with or without `RegCloseKey'()`). Probably my original
observation was somewhat bogus.

> I will re-measure the performance last time, then I think we can close this issue.

I'm basically ok with this ticket. Feel free to close it once you think it's done.

**Comment by daipom** [comment]
I have re-measured on 7da2b706bd7d73b5f00876fcaae085b5a8924230.

I don't know why, but `% processor time` is also improved.
It takes no longer 15% ~ 25%.

It's hard to consider that this much improvement was achieved
only by the timing of the initialization process...
but the performance is now not significantly inferior to prometheus.

|                                                  | Fluentd | Prometheus |
|--------------------------------------------------|---------|------------|
| Time to update data                              | 0.074s  | 0.049s     |
| Aerage % processor time to update data (every 3 sec in 3min) | 2.8%    | 0.42%      |

![2021-12-21_17h52_09](https://user-images.githubusercontent.com/12229857/146901044-f46cddca-754a-48e5-90b6-27f812bb5514.png)

Result Data
[measured_data.zip](https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/files/7751198/measured_data.zip)

Environment
* Machine
  * Windows 10 Home
  * Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
  * RAM: 16.0 GB
* Fluentd
  * fluentd 1.14.3 installed by gem
* This plugin
  * on the commit: 7da2b706bd7d73b5f00876fcaae085b5a8924230
* Prometheus windows exporter
  * 0.16.0

# How to measure

## Time to update data

This plugin

* Run test code `HKeyPerfDataReaderTest::test_read_speed` by `$ rake test`.

Prometheus windows exporter

* `$ .\windows_exporter.exe --collectors.enabled="cpu,memory,logical_disk,net,os"`
* Run followin script and calculates the average value

```ruby
require 'benchmark'
require 'uri'
require 'net/http'

10.times do
  result = Benchmark.realtime do
    uri = URI("http://localhost:9182/metrics")
    Net::HTTP.get_response(uri)
  end
  p result
end
```

## `% processor time` to update data

This plugin

* Run fluentd by `$ fluentd -c {config_path}`
* Set config as follows to update data every 3 seconds.

```
<source>
  @type windows_exporter
  tag windows_exporter
  scrape_interval 3
</source>
<match windows_exporter>
  @type file
  path {output_path}
</match>
```

Prometheus windows exporter

* `$ .\windows_exporter.exe --collectors.enabled="cpu,memory,logical_disk,net,os"`
* Run following python script to make this to update data every 3 seconds.
  * Unintentionally, I used python for this one, but ruby is fine too.

```python
import requests
import time

while True:
    requests.get('http://localhost:9182/metrics')
    time.sleep(3)
```

Get `% processor time` of the process by using powershell commands

* This plugin: `Get-Counter "\Process(ruby*)\% processor time"`
  * Make sure there are no other ruby processes.
* Prometheus windows exporter: `Get-Counter "\Process(windows_exporter)\% processor time"`

I used [this powershell script](https://github.com/daipom/WindowsPowershellFunctions/blob/main/MonitorProcess.ps1)

* `MonitorProcess.ps1 "ruby*" -MonitorList ProcessorTime -Interval 0`
* `MonitorProcess.ps1 "windows_exporter" -MonitorList ProcessorTime -Interval 0`
